[[coreutils]]
arch = "aarch64"
git-tree-sha1 = "661a8995dbf09e71f90cb7bc9e95124a690477e7"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "f377052ba5b14809bbebdd2c220415f1e5944b318dfcfc14d92d7dfd58fdc41d"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.aarch64-linux-gnu.tar.gz"
[[coreutils]]
arch = "aarch64"
git-tree-sha1 = "820abef411f5c1f612ac4ec9123db77304413c4c"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "9e360c99a623b26f865b55b5b4f8ca42d59fa9a5257e7482390c2b8d279a2cea"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.aarch64-linux-musl.tar.gz"
[[coreutils]]
arch = "aarch64"
git-tree-sha1 = "25f3d4302dcbeee8b280c59d00f399a387536f05"
os = "freebsd"

    [[coreutils.download]]
    sha256 = "1516147f680ae352a51e6737363a32df7f235476423cb433d66349978f86e842"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.aarch64-unknown-freebsd.tar.gz"
[[coreutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f620f4be9591fda3af7e115f20cd329afd1a527"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "f560777ac589750cd02d51b240284f9757bb2514d0fe25fd99ba591cef79c7c1"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.armv6l-linux-gnueabihf.tar.gz"
[[coreutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0ff74d72f544a5e6b03cc860973e59024725c568"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "853760d021f60f15d2cd4d93dff9d6edd99c3b93c7eaee978983f21f0e486a1d"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.armv6l-linux-musleabihf.tar.gz"
[[coreutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e631c3d6df0e707377e920cd8283b809e64d133"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "b65b4478dcf5ed7b1554fdd6bb8d384f271042e10c33989f2653d5201b28ebd3"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.armv7l-linux-gnueabihf.tar.gz"
[[coreutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "010085d776c8e50327ad6a9644855db7e22e4659"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "962ffb777c81d81ecc430e1c331fdbbc94ea93b5072e82e597a00fdae0e90930"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.armv7l-linux-musleabihf.tar.gz"
[[coreutils]]
arch = "i686"
git-tree-sha1 = "44ad1ed8c78604f4756a81f8a8ce1e3622c1f5f9"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "6edfcb77af01a78364a53cc70633b5ab79294a07e7a0072372da7ab8274324a3"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.i686-linux-gnu.tar.gz"
[[coreutils]]
arch = "i686"
git-tree-sha1 = "c873909896a11f52c18f9b3ba0c6335f807e63ea"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "0b8d9eb0de9c9e2d49cbd73201b4451aa51dea1f22860024cdb4dbe5366fa441"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.i686-linux-musl.tar.gz"
[[coreutils]]
arch = "powerpc64le"
git-tree-sha1 = "9281d6361ba2863245dfb885251dc744c200038b"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "2ca6df7f5a7f7786932add79101bc4b487fa3bee7aa46a8ffc2bae540b7750db"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.powerpc64le-linux-gnu.tar.gz"
[[coreutils]]
arch = "riscv64"
git-tree-sha1 = "1074d2d61d3ec76882ebd3db291b6f36d453dbd0"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "06bce3b1e73581f11f632783d5d494ea9f2d9df2106e35334a104e6173062f79"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.riscv64-linux-gnu.tar.gz"
[[coreutils]]
arch = "x86_64"
git-tree-sha1 = "14e0adec936ef0556f44198d5f187f8f3a24908a"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "2b1e9dbc30d4f5dc9508557e336c86403f287311e0660cdaaa397cab21563c5c"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.x86_64-linux-gnu.tar.gz"
[[coreutils]]
arch = "x86_64"
git-tree-sha1 = "4981dab41c1aa8e629299539caab77806d291739"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "3fb6339341f4157cbe8465c80dc55b25d51a4fbc05980c341b2f4fd45c185211"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.x86_64-linux-musl.tar.gz"
[[coreutils]]
arch = "x86_64"
git-tree-sha1 = "bd944e59821e4df8ca2afc9659e1010cc0bc0e83"
os = "freebsd"

    [[coreutils.download]]
    sha256 = "769349f3397f6c81e466a21e453981fbbde3e26a4af3eb8cafad3192f14f8314"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.9.0+0/coreutils.v9.9.0.x86_64-unknown-freebsd.tar.gz"
